version: '3'

services:
    mailbuddy:
        image: ghcr.io/printerboi/siteware_business_dev:latest
        ports:
            - '3002:3000'
        volumes:
            - ./stats:/app/stats

    qdrant:
      image: qdrant/qdrant:latest
      restart: always
      container_name: qdrant
      ports:
        - 6333:6333
        - 6334:6334
      expose:
        - 6333
        - 6334
        - 6335
      volumes:
        - ./qdrant_data:/qdrant_data