version: '3'

services:
    mailbuddy:
        image: ghcr.io/printerboi/siteware_business_prod:latest
        ports:
            - '3002:3000'
        volumes:
            - ./stats:/app/stats
        networks:
            - mailbuddynetwork
            - proxynetwork

    qdrant:
      image: qdrant/qdrant:latest
      restart: always
      container_name: qdrant
      ports:
        - 6333:6333
        - 6334:6334
      expose:
        - 6333
        - 6334
        - 6335
      volumes:
        - ./qdrant_data:/qdrant_data
      networks:
        - mailbuddynetwork

networks:
  mailbuddynetwork:
    name: mailbuddynetwork
  proxynetwork:
    name: swag_proxynetwork
    external: true