version: '3'

services:
    mailbuddy:
        build:
            context: ../../
            dockerfile: docker/production/Dockerfile
        image: mailbuddy
        ports:
            - '3002:3000'
        networks:
            - mailbuddynetwork
            - proxynetwork


networks:
  mailbuddynetwork:
    name: mailbuddynetwork
  proxynetwork:
    name: swag_proxynetwork
    external: true