# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  Registry: ghrc.io
  IMAGE_NAME: ${{ github.actor }}/sitware-business-dev:$(date +%s)

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # - run: npm run build --if-present
    - run: npm run lint

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create sentry File
      run: |
          echo -e "${{ secrets.SENTRY_FILE }}" > .sentryclirc

    - name: Create Firebase File
      env:
        JSON: ${{ secrets.FIREBASE_FILE }}
      run: |
          echo $JSON > mailbuddy_priv_key.json

    - name: Create .env File
      run: |
          echo -e "${{ secrets.ENV_FILE }}" > .env
    - name: Build the Docker image
      run: |
        docker build . --file docker/production/Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}